---
galaxy_info:
  author: "Casey Sparks"
  description: "Sets up my dotfiles"
  issue_tracker_url: "https://github.com/caseysparkz/ansible"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17.10"
  galaxy_tags:
    - "dotfiles"
    - "linux"
  platforms:
    - name: "Debian"
      versions: ["bookworm"]
dependencies: []
