---
- name: "Create ~/.ssh/"
  loop:
    - "{{ ansible_env.HOME }}/.ssh/"
    - "{{ ansible_env.HOME }}/.ssh/keys"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0700"
