---
namespace: "loganpageler"
name: "environment"
version: "1.1.10"
readme: "README.md"
authors: ["Logan Pageler <pagelerlogan@gmail.com>"]
description: "An Ansible collection to set up my preferred user environment."
license: ["GPL-2.0-or-later"]
tags: ["linux"]
dependencies:
  community.general: ">=10.7.0,<11.0.0"
repository: &repo "https://github.com/loganpageler/env"
documentation: "https://github.com/loganpageler/env/blob/main/collections/loganpageler/environment/README.md"
homepage: *repo
issues: "https://github.com/loganpageler/ansible/issues"
build_ignore: []
