---
- name: "Configure IO scheduler"
  become: true
  tags: ["ioscheduler"]
  ansible.builtin.blockinfile:
    path: "/etc/modules-load.d/iosched.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    create: true
    block: |
      bfq
      mq-deadline
      kyber-iosched
