---
galaxy_info:
  author: "Casey Sparks"
  description: "Sets resonable password requirements via PAM."
  issue_tracker_url: "https://github.com/caseysparkz/ansible/issues"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17"
  galaxy_tags:
    - "linux"
    - "security"
  platforms:
    - name: "Debian"
      versions: ["bookworm"]
dependencies: []
