---
collections:
  - name: "./collections/loganpageler/environment"
    version: ">=1,<2"
  - name: "./collections/loganpageler/performance"
    version: ">=1,<2"
  - name: "./collections/loganpageler/security"
    version: ">=1,<2"
