---
collections:
  - name: "./collections/caseysparkz/environment"
    version: ">=1,<2"
  - name: "./collections/caseysparkz/performance"
    version: ">=1,<2"
  - name: "./collections/caseysparkz/security"
    version: ">=1,<2"
