---
collections:
  - name: "./collections/caseysparkz/environment"
    version: "1.1.1"
  - name: "./collections/caseysparkz/performance"
    version: "1.0.0"
  - name: "./collections/caseysparkz/security"
    version: "1.0.0"
