---
- name: "[packages.install]"
  become: true
  tags: ["install"]
  block:
    - name: "[packages.install.apt]"
      become: true
      tags: ["apt"]
      when: "ansible_os_family == 'Debian'"
      loop: "{{ packages_apt }}"
      ansible.builtin.apt:
        name: "{{ item.name }}"
        state: "present"
        update_cache: true
        cache_valid_time: 3600

    - name: "[packages.install.dnf]"
      become: true
      tags: ["dnf"]
      when: "ansible_os_family == 'RedHat'"
      loop: "{{ packages_dnf }}"
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "present"
        update_cache: true

    - name: "[packages.install.pacman]"
      become: true
      tags: ["pacman"]
      when: "ansible_os_family == 'ArchLinux'"
      loop: "{{ packages_pacman }}"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "present"
        update_cache: true

    - name: "[packages.install.pip]"
      become: true
      tags: ["pip"]
      loop: "{{ packages_pip }}"
      ansible.builtin.pip:
        name: "{{ item }}"
        state: "present"
        break_system_packages: true
