---
- name: "[packages]"
  tags: ["packages"]
  block:
    - name: "[packages.install]"
      ansible.builtin.import_tasks: "install.yml"

    - name: "[packages.system_services]"
      ansible.builtin.import_tasks: "system_services.yml"

    - name: "[packages.usermod]"
      ansible.builtin.import_tasks: "usermod.yml"
