---
- name: "[packages.usermod]"
  become: true
  tags: ["usermod"]
  block:
    - name: "[packages.usermod.create_groups]"
      loop: &groups ["docker"]
      ansible.builtin.group:
        name: "{{ item }}"
        state: "present"
        system: true

    - name: "[packages.usermod.add_user]"
      loop: *groups
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: "{{ item }}"
        append: true
