---
- name: "Install vim"
  become: true
  tags: ["apt"]
  when: "ansible_os_distribution == 'Debian'"
  ansible.builtin.apt:
    pkg: "vim"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
