---
- name: "Install libpam-pwquality"
  become: true
  ansible.builtin.apt:
    pkg:
      - "libpam-pwquality"
      - "libpamtest0"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Get common-passward PAM config"
  register: "common_password_file"
  ansible.builtin.stat:
    path: &file "/etc/pam.d/common-password"

- name: "Harden PAM password requirements"
  become: true
  if: false  # TODO
  when: "common_password_file.stat.exists"
  ansible.builtin.lineinfile:
    dest: *file
    regexp: "(^password\\s+requisite\\s+pam_pwquality.so)\\s+.*$"
    line: "\\1 retry=3 minlen=10 difok=3 ucredit=-1 dcredit=-1 ocredit=-1 maxrepeat=3 gecoschec"
    # validate: %s
