---
- name: "[security.auditd]"
  become: true
  tags: ["auditd"]
  block:
    - name: "[security.auditd.create_dir]"
      ansible.builtin.file:
        path: "/etc/audit/rules.d/"
        state: "directory"
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "[security.auditd.configure]"
      ansible.builtin.copy:
        src: "audit.rules"
        dest: "/etc/audit/rules.d/audit.rules"
        mode: "0644"
        owner: "root"
        group: "root"
