---
- name: "[security.iptables]"
  become: true
  tags:
    - "iptables"
    - "firewall"
  block:
    - name: "[security.iptables.install]"
      when: "ansible_os_family == 'Debian'"
      tags: ["apt"]
      loop:
        - "iptables-persistent"
        - "netfilter-persistent"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "present"

    - name: "[security.iptables.install]"
      when: "ansible_os_family == 'RedHat'"
      tags: ["dnf"]
      loop:
        - "iptables"
        - "nftables"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "present"

    - name: "[security.iptables.install]"
      when: "ansible_os_family == 'ArchLinux'"
      tags: ["pacman"]
      loop:
        - "iptables"
        - "iptables-nft"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "present"

    - name: "[security.iptables.drop_all]"
      notify: "[handler.iptables]"
      ansible.builtin.iptables:
        action: "insert"
        chain: "INPUT"
        policy: "DROP"
