---
- name: "[security.priviledge_escalation]"
  become: true
  tags: ["priviledge_escalation"]
  block:
    - name: "[security.priviledge_escalation.disable_securetty]"
      ansible.builtin.copy:
        dest: "/etc/securetty"
        owner: "root"
        group: "root"
        mode: "0400"
        content: ""
        force: false

    - name: "[security.priviledge_escalation.set_sudo_timeout]"
      ansible.builtin.lineinfile:
        backup: false
        line: "Defaults timestamp_timeout=1"
        path: "/etc/sudoers"
        state: "present"

    - name: "[security.priviledge_escalation.su.find]"
      register: "security_su"
      ansible.builtin.find:
        patterns: "^su$"
        paths:
          - "/bin"
          - "/usr/bin"

    - name: "[security.priviledge_escalation.su.disable]"
      when: "security_su.examined | length != 0"
      ansible.builtin.file:
        dest: "/bin/su"
        owner: "root"
        group: "root"
        mode: "0700"

    - name: "[security.priviledge_escalation.pkexec.find]"
      register: "security_pkexec"
      ansible.builtin.find:
        patterns: "^pkexec$"
        paths:
          - "/bin"
          - "/usr/bin"

    - name: "[security.priviledge_escalation.pkexec.disable]"
      when: "security_pkexec.examined | length != 0"
      loop: "{{ security_pkexec.files }}"
      ansible.builtin.file:
        dest: "{{ item }}"
        owner: "root"
        group: "root"
        mode: "0700"
