---
namespace: "loganpageler"
name: "security"
version: "1.0.1"
readme: "README.md"
authors: ["Logan Pageler <pagelerlogan@gmail.com>"]
description: "A collection of security improvements for Linux systems."
license: ["GPL-2.0-or-later"]
tags:
  - "linux"
  - "security"
dependencies:
  ansible.posix: ">=2.0.0,<3.0.0"
  community.general: ">=10.7.0,<11.0.0"
repository: &repo "https://github.com/Logan-Pageler/env"
documentation: "https://github.com/Logan-Pageler/env/blob/main/collections/loganpageler/security/README.md"
homepage: *repo
issues: "https://github.com/Logan-Pageler/env/issues"
build_ignore: []
