---
- name: "Install system packages"
  become: true
  when: "ansible_os_family == 'Debian'"
  tags: ["apt"]
  ansible.builtin.apt:
    pkg: "{{ packages_apt }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
