---
- name: "[security.disable_crash_reporters]"
  become: true
  when: "ansible_distribution == 'Ubuntu'"
  tags: ["crash_reporters"]
  block:
    - name: "[security.disable_crash_reporters.whoopsie]"
      tags: ["whoopsie"]
      ansible.builtin.apt:
        name: "whoopsie"
        state: "absent"
        purge: true

    - name: "[security.disable_crash_reporters.whoopsie_preferences]"
      tags: ["whoopsie"]
      ansible.builtin.apt:
        name: "whoopsie-preferences"
        state: "absent"
        purge: true

    - name: "[security.disable_crash_reporters.apport]"
      tags: ["apport"]
      ansible.builtin.apt:
        name: "apport"
        state: "absent"
        purge: true
        autoremove: true
        autoclean: true
