---
- name: "[security]"
  tags: ["security"]
  block:
    - name: "[security.auditd]"
      ansible.builtin.import_tasks: "auditd.yml"

    - name: "[security.disable_crash_reporters]"
      ansible.builtin.import_tasks: "disable_crash_reporters.yml"

    - name: "[security.fail2ban]"
      ansible.builtin.import_tasks: "fail2ban.yml"

    - name: "[security.faillock]"
      ansible.builtin.import_tasks: "faillock.yml"

    - name: "[security.iptables]"
      ansible.builtin.import_tasks: "iptables.yml"

    - name: "[security.kernel]"
      ansible.builtin.import_tasks: "kernel.yml"

    - name: "[security.passwords]"
      ansible.builtin.import_tasks: "passwords.yml"

    - name: "[security.privilege_escalation]"
      ansible.builtin.import_tasks: "privilege_escalation.yml"

    - name: "[security.ssh]"
      ansible.builtin.import_tasks: "ssh.yml"

    - name: "[security.ulimit]"
      ansible.builtin.import_tasks: "ulimit.yml"

    - name: "[security.unattended_upgrades]"
      ansible.builtin.import_tasks: "unattended_upgrades.yml"
