---
- name: "[security.passwords]"
  tags: ["passwords"]
  become: true
  block:
    - name: "[security.passwords.get_commonpassword_pam]"
      register: "common_password_file"
      ansible.builtin.stat:
        path: "/etc/pam.d/common-password"

    - name: "[security.passwords.force_strong_passwords]"
      when: "common_password_file.stat.exists"
      ansible.builtin.lineinfile:
        dest: "/etc/pam.d/common-password"
        regexp: "^.*pam_pwquality.so.*$"
        line: >
          password requisite pam_pwquality.so
          retry=3 minlen=10 difok=3 ucredit=-1 dcredit=-1 ocredit=-1 maxrepeat=3 gecoschec
