---
- name: "[security.ssh]"
  become: true
  tags: ["ssh"]
  block:
    - name: "[security.ssh.find_sshd]"
      register: "security_sshd_path"
      ansible.builtin.stat:
        path: "/usr/sbin/sshd"

    - name: "[security.ssh.harden_config]"
      when: "security_sshd_path.stat.exists"
      loop: "{{ security_ssh_config }}"
      ansible.builtin.lineinfile:
        create: true
        path: "/etc/ssh/sshd_config"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: "present"
        validate: "/usr/sbin/sshd -t -f %s"
        mode: "0644"

    - name: "[security.ssh.remove_short_dhcurves]"
      changed_when: false
      notify: "[handler.sshd]"
      ansible.builtin.shell: |
        set -o pipefail
        awk '$5 >= 3071' /etc/ssh/moduli | tee /tmp/ssh_moduli
        mv /tmp/ssh_moduli /etc/ssh/moduli
