---
- name: "[environment.bash]"
  tags: ["bash"]
  block:
    - name: "[environment.bash.symlink_bash_dir]"
      ansible.builtin.file:
        src: "bash/"
        dest: "{{ ansible_env.HOME }}/.bash"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        force: true
        state: "link"

    - name: "[environment.bash.symlink_profile]"
      ansible.builtin.file:
        src: "bash/profile"
        dest: "{{ ansible_env.HOME }}/.profile"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        force: true
        state: "link"

    - name: "[environment.bash.symlink_bashrc]"
      ansible.builtin.file:
        src: "bash/bashrc"
        dest: "{{ ansible_env.HOME }}/.bashrc"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        force: true
        state: "link"

    - name: "[environment.bash.touch_bashrc_local]"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.local"
        state: "touch"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0755"

    - name: "[environment.bash.symlink_bash_logout]"
      ansible.builtin.file:
        src: "bash/bash_logout"
        dest: "{{ ansible_env.HOME }}/.bash_logout"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        force: true
        state: "link"
