---
- name: "[environment.gnupg]"
  tags: ["gnupg"]
  block:
    - name: "[environment.gnupg.create_dir]"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.gnupg/"
        state: "directory"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0700"

    - name: "[environment.gnupg.install_agent_config]"
      ansible.builtin.copy:
        src: "gnupg/gpg-agent.conf"
        dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0600"

    - name: "[environment.gnupg.replace_config]"
      ansible.builtin.copy:
        src: "gnupg/gpg.conf"
        dest: "{{ ansible_env.HOME }}/.gnupg/gpg.conf"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0600"

    - name: "[environment.gnupg.find_role_pubkeys]"
      register: "pgp_pubkeys"
      ansible.builtin.find:
        paths: "{{ role_path }}/files/"
        patterns: "*.asc"
        recurse: false
        file_type: "file"

    - name: "[environment.gnupg.import_pubkeys]"
      loop: "{{ pgp_pubkeys.files }}"
      changed_when: false
      ansible.builtin.command:
        cmd: "gpg --import {{ item.path }}"
