---
- name: "Set up ~/"
  tags: ["filesystem"]
  loop: "{{ filesystem_paths }}"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: "directory"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0700"
