---
galaxy_info:
  author: "Casey Sparks"
  description: "Runs all security collecion roles."
  issue_tracker_url: "https://github.com/caseysparkz/ansible/issues"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17"
  galaxy_tags: ["security"]
dependencies:
  - role: "caseysparkz.security.auditd"
  - role: "caseysparkz.security.defaultdeny"
  - role: "caseysparkz.security.disablecrashreporters"
  - role: "caseysparkz.security.fail2ban"
  - role: "caseysparkz.security.faillock"
  - role: "caseysparkz.security.kernel"
  - role: "caseysparkz.security.passwords"
  - role: "caseysparkz.security.privilegeescalation"
  - role: "caseysparkz.security.ssh"
  - role: "caseysparkz.security.ulimit"
  - role: "caseysparkz.security.unattendedupgrades"
