---
- name: "Create /etc/audit/rules.d/"
  become: true
  ansible.builtin.file:
    path: "/etc/audit/rules.d/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Configure auditd"
  become: true
  ansible.builtin.copy:
    src: "audit.rules"
    dest: "/etc/audit/rules.d/audit.rules"
    owner: "root"
    group: "root"
    mode: "0644"
