---
- name: "Install git packages"
  become: true
  when: "ansible_os_family == 'Debian'"
  ansible.builtin.apt:
    pkg: &packages
      - "gh"
      - "git"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Install git packages"
  become: true
  when: "ansible_os_family == 'RedHat'"
  ansible.builtin.dnf:
    name: *packages
    state: "present"
    update_cache: true
