---
- name: "Create ~/.local/lib"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/lib/"
    state: "directory"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0700"

- name: "Symlink scripts directory"
  ansible.builtin.file:
    src: "scripts/"
    dest: "{{ ansible_env.HOME }}/.local/lib/scripts/"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    state: "link"
    force: true
