---
- name: "[performance.filesystem]"
  become: true
  tags: ["filesystem"]
  block:
    - name: "[performance.filesystem.update_fstab]"
      tags: ["fstab"]
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        regexp: "tmpfs /tmp tmpfs"
        line: "tmpfs /tmp tmpfs defaults,lazytime,noatime,nodiratime 0 0"
        state: "present"
        backup: true

    - name: "[performance.filesystem.discard_trim_enable]"
      tags:
        - "fstrim"
        - "systemd"
      ansible.builtin.systemd:
        name: "fstrim.timer"
        state: "started"
        enabled: true
        daemon_reload: true
