---
- name: "[performance.reflector]"
  become: true
  when: "ansible_os_family == 'ArchLinux'"
  notify: "[handler.reflector]"
  tags:
    - "systemd"
    - "reflector"
  community.general.pacman:
    name: "reflector"
    state: "present"
    upgrade: true
    update_cache: true
