---
- name: "[handler.reflector]"
  become: true
  tags:
    - "reflector"
    - "systemd"
  ansible.builtin.systemd_service:
    name: "reflector.service"
    state: "started"
    enabled: true
    daemon_reload: true
