---
- name: "Create subdirectories"
  tags: ["dotfiles"]
  loop: "{{ dotfiles_subdirectories }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "{{ item.mode }}"
    state: "directory"

- name: "Symlink configurations"
  tags: ["dotfiles"]
  loop: "{{ dotfiles_symlinks }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    state: "link"
    force: true
