---
- name: "[performance.install_dependencies]"
  become: true
  tags: ["install_dependencies"]
  block:
    - name: "[performance.install_dependencies]"
      when: "ansible_os_family == 'Debian'"
      tags: ["apt"]
      ansible.builtin.apt:
        name: "{{ performance_packages.apt }}"
        state: "present"
        update_cache: true
        cache_valid_time: 3600

    - name: "[performance.install_dependencies]"
      when: "ansible_os_family == 'RedHat'"
      tags: ["dnf"]
      ansible.builtin.dnf:
        name: "{{ performance_packages.dnf }}"
        state: "present"

    - name: "[performance.install_dependencies]"
      when: "ansible_os_family == 'Archlinux'"
      tags: ["pacman"]
      community.general.pacman:
        name: "{{ performance_packages.pacman }}"
        state: "present"
