# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Lint all Python files with both Pylint and Flake8.
---
name: "Validate Python code"
on:
  pull_request:
    branches: ["main"]
    paths: ["**/*.py"]
jobs:
  ruff:
    name: "ruff format --check"
    runs-on: "ubuntu-latest"
    env:
      PYTHON_MAX_LINES: 120
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"  # v4.2.2
        with:
          fetch-depth: 0

      - name: "Reformat all Python code"
        id: "ruff"
        uses: "astral-sh/ruff-action@eaf0ecdd668ceea36159ff9d91882c9795d89b49"  # v3.4.0
        with:
          args: "format --config --line-length ${{ env.PYTHON_MAX_LINES }}"
          changed-files: "true"

      - name: "Get files changed by lint"
        run: "git fetch origin main:main"

      - name: "Import PGP identity"
        id: "import_pgp"
        uses: "crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec"  # v6.3.0
        with:
          gpg_private_key: "${{ secrets.ORG_SIGNING_KEY }}"
          passphrase: "${{ secrets.ORG_SIGNING_KEY_PASSPHRASE }}"
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: "Auto-commit/push changes"
        id: "auto_commit"
        uses: "stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403"  # v5.2.0
        with:
          commit_author: "${{ steps.import_pgp.outputs.name }} <${{ steps.import_pgp.outputs.email }}>"
          commit_user_email: "${{ steps.import_pgp.outputs.email }}"
          commit_user_name: "${{ steps.import_pgp.outputs.name }}"
          commit_message: "style(python): Auto-reformatted Terraform configs"
          file_pattern: "*.py"
