---
- name: "Enable fstrim.timer"
  become: true
  tags:
    - "filesystem"
    - "fstrim"
    - "systemd"
  ansible.builtin.systemd:
    name: "fstrim.timer"
    state: "started"
    enabled: true
    daemon_reload: true
